export default {
  products: [
    {
      _id: "1",
      name: "First product",
      category: "bag",
      image: "./src/images/product-1.jpg",
      Price: 99999,
      brand: "channel",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "First product",
      category: "bag",
      image: "./src/images/product-1.jpg",
      Price: 99999,
      brand: "channel",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "3",
      name: "First product",
      category: "bag",
      image: "./src/images/product-1.jpg",
      Price: 99999,
      brand: "channel",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "4",
      name: "First product",
      category: "bag",
      image: "./src/images/product-1.jpg",
      Price: 99999,
      brand: "channel",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "5",
      name: "First product",
      category: "bag",
      image: "./src/images/product-1.jpg",
      Price: 99999,
      brand: "channel",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "6",
      name: "First product",
      category: "bag",
      image: "./src/images/product-1.jpg",
      Price: 99999,
      brand: "channel",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "7",
      name: "First product",
      category: "bag",
      image: "./src/images/product-1.jpg",
      Price: 99999,
      brand: "channel",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "8",
      name: "First product",
      category: "bag",
      image: "./src/images/product-1.jpg",
      Price: 99999,
      brand: "channel",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
  ],
};
